server:
  port: 8080

spring:
  application:
    name: MongoFlexFullTextSearch
  data:
    mongodb:
      host: ${MONGODB_HOST}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      port: ${MONGODB_PORT}
      database: text_search
      authentication-database: ${MONGODB_AUTH_DB}

special:
  org:
    watching:
      database-path: ${DATABASE_PATH}

      databases:
        catalog_manager:
          -
            collection_name: airport
            text_fields: name
          -
            collection_name: protectTarget
            text_fields: name
          -
            collection_name: responsibility_area
            text_fields:
              - name
              - unitId
          -
            collection_name: vsis_fire_power
            text_fields:
              - unitId
              - weaponModel.description

        command_report:
          -
            collection_name: command
            text_fields: name
          -
            collection_name: forms
            text_fields: name

        daily_report:
          - collection_name: daily_report
            text_fields: name
          - collection_name: history_logs
            text_fields: name