server:
  port: 8080

spring:
  application:
    name: MongoFlexFullTextSearch
  #  This is our database which saves text search
  data:
    mongodb:
      host: our_host
      username: our_uname
      password: our_passwd
      port: 123123 # our_port
      database: our_db_for_saving_text_search_index
      authentication-database: our_auth_db
      mapKeyDotReplacement: ->

# This is the database that need watching (using their authentication - at least read permission)
special:
  org:
    watching:
      databases:
        - database: db_name
          host: host_name
          username: uname
          password: passwd
          port: 123456
          authentication-database: auth_db_name
          collections:
            - name: collection1
              id-name: _id # optional
              text-fields:
                - field1
                - field2
            - name: collection2
              id-name: specialIdName # specifier if id-name is difference from default
              text-fields:
                - field3.subfield
                - field4

        - database: db_name
          host: host_name2
          username: uname
          password: passwd
          port: 123456
          authentication-database: auth_db_name
          collections:
            - name: collection1
              text-fields:
                - field1
                - field2
            - name: collection2
              text-fields: field0